notifications:
  email:
    recipients:
      - dtulyakov@gmail.com
      - dtulyakov.log@gmail.com

#addons:
#    code_climate:
#        repo_token: "$CLIMATE_TOKEN"

sudo: required

language: perl

services:
  - docker

before_install:
- docker build -t dtulyakov/perl:latest .
- docker run --rm -v $(pwd):/app dtulyakov/perl:latest sh -c "/app/test.sh"

script:
- date

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push dtulyakov/perl:latest;
    fi
